### ISSUE TITLE
InitializationERROR: Unknown custom metadata item kind: 6

### ISSUE THREAD

**Issue by InsightLive** [spouliot/gendarme#9]
**Gendarme v2.10.0.0**

When I try from gendarme-wizard, got below error in **Analysis Results** page.
Stack trace: Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item kind: 6
   at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction..ctor(String module, ManProcSym proc, BitAccess bits)
   at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(String module, BitAccess bits, UInt32 limit, Boolean readStrings)
   at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, BitAccess bits, Boolean readAllStrings, Int32& age, Guid& guid)
   at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Boolean readAllStrings, Int32& age, Guid& guid)
   at Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   at Gendarme.Framework.Rocks.ModuleRocks.LoadDebuggingSymbols(ModuleDefinition self)
   at Gendarme.Framework.Runner.Initialize()
   at Gendarme.GuiRunner.Execute()

It gives the result without any error, when I click on Back and then again click on Next.

It also fails on console with,
**InitializationERROR: Unknown custom metadata item kind: 6**

**Comment by dramatictone** [comment]
Is there any known fix to this one? I also get the same error.
